import './globalStyles/normalize.css';
import './globalStyles/globals.css';
import './globalStyles/header.css';
import './globalStyles/menu.css';
// import './globalStyles/mobile-navbar.css';
// import './globalStyles/catalog-menu.css';
// import './globalStyles/search-modal.css';
// import './globalStyles/cart-popup.css';
// import './globalStyles/footer.css';
// import './globalStyles/slick-theme.css';
// import './globalStyles/slick.css';
// import './globalStyles/auth-popup.css';
// import './globalStyles/header-profile.css';
// import './globalStyles/cookie-popup.css';
// import './globalStyles/breadcrumbs.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Layout } from '@/components/layouts/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Layout> {children}</Layout>
      </body>
    </html>
  );
}
